### ISSUE TITLE
Fails to get imports - OtherErr(Error("unknown variant `OBJ`))

### ISSUE THREAD

**Issue by XVilka** [radareorg/radeco#256]
![image](https://user-images.githubusercontent.com/203261/54010184-b8aa7200-41a8-11e9-9cc1-74648a73c6cb.png)

**Comment by XVilka** [comment]
@Mm7 related to https://github.com/radareorg/radeco-lib/pull/255

**Comment by Mm7** [comment]
Based on the error message, it seems that there is a problem during the deserialization JSON -> Rust structs due to a missing enum entry (OBJ). There is an entry called `Object`, (https://github.com/radare/radare2-r2pipe-api/blob/master/rust/src/structs.rs#L154-L169), probably it should be renamed into `Obj`. 

I can't reproduce the bug here (I'm working on debian, probably we have different versions of `/bin/ls`). Please, can you upload your `ls` binary? Thank!

edit: Nevermind, I found your ls on #251. I'm pretty sure that r2 outputs always `OBJ` instead of `OBJECT` (https://github.com/radare/radare2/blob/70ad8cf5ddc8cb8c6f7eab2014238a51837c041d/libr/include/r_bin.h#L103)

edit2: @XVilka  https://github.com/radare/radare2-r2pipe-api/pull/20 fixes the issue here. Can you double check please?

**Comment by XVilka** [comment]
It is fixed now, I can confirm. Now it packing on #251 as before 👍
